# This workflow builds and publishes @sbac/sbac-ui-kit using basic 'npm publish'.
# For it to work, create a secret called NPMJS_AUTH_TOKEN and set it to a
# publish token created at npmjs.org with an authorized user.
#
# Currently it builds and publishes when a commit is made to develop.
# NOTE: the developer is responsible for bumping the version number (in package.json).
name: Node.js Build and Publish
on:
  push:
    branches:
      - develop
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          registry-url: 'http://registry.npmjs.org'
          scope: '@sbac'
      - run: npm install
      - run: npm run build
      - run: npm whoami ||:; cat /home/runner/work/_temp/.npmrc; echo "TOKEN=${NODE_AUTH_TOKEN},${#NODE_AUTH_TOKEN},${NODE_AUTH_TOKEN:24}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
